### ISSUE TITLE
Authenication error

### ISSUE THREAD

**Issue by JerryJelinek** [andrew0/SiriusXM#20]
Been using this since Oct 2019 and love it.   Enables me to time shift record content from SiriusXM. 

Everything worked fine on Tuesday 4/28/2020.    When I tried to get the updated channel list on Friday 5/1, I get an authentication error.   I have tried a few more times and still get the error.  

Have no idea on what has changed, but the python code no longer goes further.  

Hoping this is easy to fix.   Will miss my regular program recording.

**Comment by neilyboy** [comment]
I believe kryptek found that they changed a cookie name

```bash
def is_logged_in(self):
        return 'SXMAUTH' in self.session.cookies
```

should now be

```bash
def is_logged_in(self):
        return 'SXMAUTHNEW' in self.session.cookies
```

hopefully that resolves your issue.


Thanks to kryptek!
https://github.com/kryptek/SiriusXM/commit/463d5e71c0380b09b081816ad56e0c167e3d8c00

**Comment by kryptek** [comment]
^ what he said. Thanks!

**Comment by JerryJelinek** [comment]
WORKS!!!!  Thank you.
