### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by silverbullettruck2001** [andrew0/SiriusXM#21]
I am trying to use this script, but it always says that it is unable to authenticate.  I verified that the username (in my case my email address) and my password work correctly if I try to login at `https://player.siriusxm.com/login` but it doesn't seem to work with this script.  Any ideas on what to try?  Here's the log when I try to connect via VLC to a channel.

```python3 sxm.py MyUsername@gmail.com 'myPassword' -p 8888
08.May 2020 18:54:13 <SiriusXM>: Unable to authenticate because login failed
08.May 2020 18:54:13 <SiriusXM>: Unable to authenticate
08.May 2020 18:54:13 <SiriusXM>: Unable to get channel list
----------------------------------------
Exception happened during processing of request from ('192.168.0.189', 49565)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "sxm.py", line 323, in do_GET
    data = sxm.get_playlist(self.path.rsplit('/', 1)[1][:-5])
  File "sxm.py", line 227, in get_playlist
    guid, channel_id = self.get_channel(name)
  File "sxm.py", line 313, in get_channel
    if x.get('name', '').lower() == name or x.get('channelId', '').lower() == name or x.get('siriusChannelNumber') == name:
AttributeError: 'NoneType' object has no attribute 'get'
----------------------------------------
08.May 2020 18:54:13 <SiriusXM>: Unable to authenticate because login failed
08.May 2020 18:54:13 <SiriusXM>: Unable to authenticate
08.May 2020 18:54:13 <SiriusXM>: Unable to get channel list
----------------------------------------
Exception happened during processing of request from ('192.168.0.189', 49566)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "sxm.py", line 323, in do_GET
    data = sxm.get_playlist(self.path.rsplit('/', 1)[1][:-5])
  File "sxm.py", line 227, in get_playlist
    guid, channel_id = self.get_channel(name)
  File "sxm.py", line 313, in get_channel
    if x.get('name', '').lower() == name or x.get('channelId', '').lower() == name or x.get('siriusChannelNumber') == name:
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by neilyboy** [comment]
Refer to closed ticket. 

https://github.com/andrew0/SiriusXM/issues/20

**Comment by silverbullettruck2001** [comment]
Thanks!  That fixed it, but now when it works I start playing a channel via VLC and it stops after about 20 seconds.  The player just hangs.  Any ideas what would cause that?

**Comment by neilyboy** [comment]
Interesting,  I have it running on a raspberry pi as well as an Ubuntu 18.04 (soon to be 20.04) server and have not seen that issue. Tried a reboot?  Is it always 20 seconds?  HLS streams are I believe in 10 sec chunks.  You signed in elsewhere with the same credentials?  Sounds like it may be logging in and then another device kicking it.

**Comment by silverbullettruck2001** [comment]
It seems to be 19 seconds exactly that it stops.  Her's my setup.  Rpi3 running python, hooked up to a speaker via 3.5mm jack, and ethernet.  The pi is running the sxm script.  On my desktop I started VLC, clicked `Media>Open Network Stream` and entered the URL to the service running on the pi (`http://192.168.0.46:8888/totally70s.m3u8`).  The music starts to play at timestamp 17:48:36.  It plays for 19 seconds and then stops at 17:48:55.

Here's what is logged to the terminal session while it plays:
```192.168.0.189 - - [09/May/2020 11:51:41] "GET /totally70s.m3u8 HTTP/1.1" 200 -
192.168.0.189 - - [09/May/2020 11:51:42] "GET /key/1 HTTP/1.1" 200 -
192.168.0.189 - - [09/May/2020 11:51:42] "GET /AAC_Data/totally70s/HLS_totally70s_256k_v3/totally70s_256k_1_050939060971_00084868_v3.aac HTTP/1.1" 200 -
192.168.0.189 - - [09/May/2020 11:51:42] "GET /AAC_Data/totally70s/HLS_totally70s_256k_v3/totally70s_256k_1_050939070738_00084869_v3.aac HTTP/1.1" 200 -
192.168.0.189 - - [09/May/2020 11:51:46] "GET /AAC_Data/totally70s/HLS_totally70s_256k_v3/totally70s_256k_1_050939080489_00084870_v3.aac HTTP/1.1" 200 -
```
If I click on the 'Next' button in VLC it will start playing again, but only for another 19 seconds.  I have tried this with other channels as well.  I am not sure if its a VLC thing or something with the script though.  

Here is a link to where I put the the debug logs from VLC when it is playing, and then I hit 'Next' to start it up again:

[https://controlc.com/f0d7c4f0](https://controlc.com/f0d7c4f0)

I see that in both cases it ends when this is logged: `main debug: resampling stopped (drift: -28741 us)` but I am not sure why it happens.  When I click 'Next' this is logged: `main debug: incoming request - stopping current input` and then the stream starts playing again.

Thoughts?

**Comment by neilyboy** [comment]
That seems strange.  You don't have music streaming in a web browser elsewhere correct?  Have you tried from vlc on a phone or other device?  It doesn't sound like the script is the issue as you are able to seek again and it works... very odd behavior for sure.  Worst case scenario I can get you a link to one of my boxes to try (either zero-tier you in or forward 8888).
Neil

**Comment by silverbullettruck2001** [comment]
Nope, this is the only place I am testing with right now.  I just tried testing from vlc on my phone and I get the same behavior.  Do you think there is anything with my python setup that could be causing it?  I just installed the basic python3 library using apt and it installed any of the dependencies, but that was it.  Not sure what else to try.  I don't get why it stalls out.

**Comment by silverbullettruck2001** [comment]
I setup port forwarding on my firewall if you want to try to access it?  Just let me know how I can securely get you the details.

**Comment by neilyboy** [comment]
Sorry my mothers day gift to the wifey was to get her pool open.  9 hours later in halfway there lol. Fell free to shoot me an email.  neilyboy@gmail.com  ill get you my server info so you can try it and ill try yours. 

I just threw raspbian on a pi3 and had no issues (i also just created a free Canada account to test). It worked as well. 

Neil

**Comment by asingletary** [comment]
> Refer to closed ticket.
> 
> #20

Updated:

'def is_logged_in(self):
        return 'SXMAUTHNEW' in self.session.cookies
`

Still receiving authentication error, and verified my username/pw is working with the web player.

`09.May 2020 22:19:32 <SiriusXM>: Received status code 403 for method 'modify/authentication'
09.May 2020 22:19:32 <SiriusXM>: Unable to authenticate because login failed
09.May 2020 22:19:32 <SiriusXM>: Unable to authenticate
09.May 2020 22:19:32 <SiriusXM>: Unable to get channel list
`

Any help is appreciated.  Thank You.

**Comment by silverbullettruck2001** [comment]
So, I blew away my RPi image and reimaged the card.  I didn't update any of the software, just put the script on the RPi and tried starting it and accessing it remotely from VLC on my PC.  Same result.  Thinking it might be a network issue, I installed VLC locally on the RPi and tried accessing it via 127.0.0.1, same result.  I am not sure what is causing this since you said you have it working fine on your Rpi3 as well.  There must be something different that I am doing.  Could you outline the steps you are doing to get it going on your RPi?  I still have the port forwarding setup, so you can try it with the details that I sent to your email address.

**Comment by neilyboy** [comment]
You sent me an email?  I just went through my inbox and trash and didn't see anything.  Let me look again. 
Neil

**Comment by silverbullettruck2001** [comment]
yeah, the subject line was "Server".

**Comment by mhanu** [comment]
I'm pretty sure it's the VLC. I have exactly the same problem with VLC 3.0.10 under MacOS. If I play the stream with Quicktime the problem does not occur.

**Comment by greg12579** [comment]
I agree, the cookie name change didn't seem to fix the issue with authentication. Can anyone confirm whether their client is working? If so did you make any additional changes?
I am getting a 403 error: 
 Received status code 403 for path 'modify/authentication'

The only thing I notice is that there is a cachebuster get parameter being passed to the authentication within the chrome browser (if I login with chrome)
There are also some additional post parameters being passed by a real browser.

**Comment by silverbullettruck2001** [comment]
@greg12579 I was able to get this working.  The issue I was facing was specific to VLC.  If I use Chrome or almost anything else it works fine.  Also worth noting, I am now using VLC 3.0.11 on my Windows PC and it seems to work fine.
